### ISSUE TITLE
Flutter 3.22.1 build failed

### ISSUE THREAD

**Issue by ClubAce** [parsadoc/simple_accordion#1]
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (8 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3

pubspec.yaml
simple_accordion: ^0.1.4

../../../.pub-cache/hosted/pub.dev/simple_accordion-0.1.4/lib/widgets/AccordionItem.dart:70:56: Error: The getter 'headline1' isn't defined for the class 'TextTheme'.

**Comment by jaxnz** [comment]
Yep, same issue.. Ill create PR

**Comment by jaxnz** [comment]
Feel free to use my fork until @parsadoc can merge and upload to pub.dev :)

``` 
simple_accordion:
    git: git@github.com:jaxnz/simple_accordion.git
```

**Comment by parsadoc** [comment]
Thanks to the @jaxnz.
new version ([v0.1.5](https://pub.dev/packages/simple_accordion)) uploaded to pub.
